language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - rbx-2.2.9
  - jruby-1.7.16
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y swig
  - git clone https://github.com/cmusphinx/sphinxbase.git
  - cd sphinxbase
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - git clone https://github.com/cmusphinx/sphinxtrain.git
  - cd sphinxtrain
  - ./autogen.sh
  - ./configure
  - sudo make install
  - cd ..
  - sudo ldconfig